### ISSUE TITLE
Pick a license

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/rfcs#1]

**Comment by tanneberger** [comment]
@lhstrh what the rust folks did was putting them under Apache or MIT and I think the author of an rfc can choose which one he likes more. (https://github.com/rust-lang/rfcs?tab=readme-ov-file#license)

The IETF uses the Revised BSD License. (https://trustee.ietf.org/assets/the-ietf-trusts-copyrights-and-licenses/)

**Comment by cmnrd** [comment]
Why not simply use the two clause BSD license as well? Or maybe the ISC license (which is a simplified successor of both 2-clause BSD and MIT).

**Comment by tanneberger** [comment]
> Why not simply use the two clause BSD license as well? Or maybe the ISC license (which is a simplified successor of both 2-clause BSD and MIT).

Agreed, I would also prefer two clause BSD license.

**Comment by lhstrh** [comment]
For the sake of simplicity, I think it's a good idea to just continue with BSD-2.

**Comment by cmnrd** [comment]
Contributors should have the option to choose another license for their RFC by explicitly stating this in the RFC. I will make this part of the guide.

**Comment by lhstrh** [comment]
What is the rationale behind this? We don't allow that with the source code checked into the lingua-franca repo either. Seems like excess generality to me...

**Comment by lhstrh** [comment]
Looks like this is addressed in #2.
